### ISSUE TITLE
create a benchmark framework that can be invoked by each protocol example

### ISSUE THREAD

**Issue by bengarishodge** [bahodge/kgpmp-prototype#3]
# Description

The idea is to have kobold use a single connection to communicate bidirectionally between `node` and `client`. This means that we have to both send and receive data on both. I think the best benchmark for pure performance would be a simple pubsub model implemented in exactly the same way across each protocol. 

A publisher should publish a fixed length of bytes a number of times using a persistent connection. The `server` should forward those messages to `n` number of subscribers. I think the simplest way to do this is with a map and a loop. No reason to go ham. 

## Todo

- [ ] create a publisher
- [ ] create a server that can parse a message
- [ ] forward a message to another client
- [ ] validate that the message was received
- [ ] measure the overall performance of sending/receiving a message.
